# Azure DevOps PoC for ABI - Implement a Pipeline
# Added steps that build, run tests, deploy:
# Step1:
# Step2:
# Step3:
# Step4:
# Step5:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Maven@3
  displayName: 'Maven: Build'
  inputs:
    mavenPomFile: 'pom.xml'
    #mavenOptions: '-Xmx1024m'
    javaHomeOption: 'JDKVersion'
    #javaHomeOption: 'Path'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    #jdkDirectory: '/usr/java/jdk'
    publishJUnitResults: false
    #testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: package deploy:deploy mule:deploy

- task: CopyFiles@2
  displayName: 'Copy jar and pom to artifact staging directory'
  inputs:
    contents: |
      target/*.jar
      pom.xml
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishPipelineArtifact@0
  displayName:  'Publish artifacts'
  inputs:
    artifactName: 'build'
    targetPath: $(Build.ArtifactStagingDirectory) 
