# Azure DevOps PoC for ABI - Implement a Pipeline
# Added steps that build, run tests, deploy:
# Step1:
# Step2:
# Step3:
# Step4:
# Step5:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'settings.xml'
