# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*

pool:
  name: 'Default'
  vmImage: 'ubuntu-latest'

steps:

-task:Maven@3
  displayName: 'Maven: Set version'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx1024m'
    # javaHomeOption: 'JDKVersion'
    javaHomeOption: 'Path'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    jdkDirectory: '/usr/java/jdk'
    publishJUnitResults: false
    goals: 'versions:set -DnewVersion=1.$(Build.BuildNumber) --settings $(Agent.TempDirectory)/settings.xml'

-task: Maven@3
 displayName: 'Maven: Build'
 inputs:
mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx1024m'
      # javaHomeOption: 'JDKVersion'
      javaHomeOption: 'Path'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      jdkDirectory: '/usr/java/jdk'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package -e -DmuleDeploy -P ci --settings $(Agent.TempDirectory)/settings.xml'
