#%RAML 1.0 Library
types:
  brand:
    type: object
    properties:
      brandId:
        type: string
        example: "238932"
        description: primary Id to identify Brands
      name:
        type: string
        example: MICHELOB ULTRA
        description: Brand Name
  
  attribute:
   properties:
     attribute:
       type: string
       example: "responseData.manufacturerAsset.manufacturerName"
       description: ""
     value:
       type: string
       example: "ANHEUSER-BUSCH INC."
       description: ""

  image:
    properties:
      brandId:
        type: string
        example: "2389322"
        description: primary identifier for brand
      blobname: 
        type: string
        example: ""
        description: image identifier GUID in Blob container
      mainImage:
        type: boolean
        example: true
        description: Flag for main image identifier (Unused at this time)
      viewCode:
        type: string
        example: "C3"
        description: "Code that defines whether the image is color or black & white and also the angle of the image.
\n\n Standard View Codes:
\n* CF - Color Front
\n* CR - Color Right
\n* CL - Color Left
\n* BF - B&W Front
\n* BR - B&W Right
\n* BL - B&W Left
\n* BC - Barcode
\n* IN - Ingredient Statement
\n* SF - Supplemental Facts Label
\n* NF - Nutrition Fact Panel
\n* DF - Drug Fact Panel
\n* FC - Feeding Chart
\n* PV - Product Packaging Bundle
\n* shelfman - Shelf Management Bundle"
      "type":
        type: string
        example: "kwikee:BMP"
        description: Refers to anything special about the subject in the images.
      promotion:
        type: string
        example: "MIDN"
        description: can be ignored
      mimeType:
        type: string
        example: "image/bmp"
        description: mimeType of asset
      width:
        type: string
        example: "255"
        description: width of image
      height:
        type: string
        example: "200"
        description: height of image
      lastUpdatedDateTime:
        type: string
        example: "2019-11-26T11:17:17"
        description: date time of when the asset was pulled from Kwikee and moved to 6Pack
  
  brands:
    type: object
    properties:
      value: brand[]
  
  brandMetaData:
    type: object
    properties:
      brandId:
        type: string
        example: "2389322"
        description: primary identifier of brand
      attributes:
        type: attribute[]
      folderPath:
        type: string
        example: "michelob-family/michelob-ultra/brand-logos"
        description: folder path used for S3 Bucket

  brandImages:
    type: object  
    properties:
      values: image[]

          
          
      